# Generated by Django 4.2.26 on 2025-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="achievements",
        ),
        migrations.AddField(
            model_name="trainer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="trainers/",
                verbose_name="Фото тренера",
            ),
        ),
    ]
