# Generated by Django 4.2.26 on 2025-12-12 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0002_remove_trainer_achievements_trainer_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="img",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(14),
                    django.core.validators.MaxValueValidator(120),
                ],
                verbose_name="Возраст",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
    ]
