# Generated by Django 4.2.26 on 2025-12-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0003_remove_userprofile_img_userprofile_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="Полное имя"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["full_name"], name="users_full_na_0edea9_idx"),
        ),
    ]
