# Generated by Django 4.2.26 on 2025-12-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0004_alter_userprofile_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["phone"], name="users_phone_af6883_idx"),
        ),
    ]
