# Generated by Django 4.2.26 on 2025-12-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0005_alter_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Среднее арифметическое всех оценок",
                max_digits=3,
                verbose_name="Средний рейтинг",
            ),
        ),
    ]
