# Generated by Django 4.2.26 on 2025-12-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0006_trainer_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Назначена"),
                    ("cancelled", "Отменена"),
                    ("completed", "Завершена"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
