# Generated by Django 4.2.26 on 2025-12-13 01:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0008_update_record_statuses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отзыв на тренера",
                "verbose_name_plural": "Отзывы на тренеров",
            },
        ),
        migrations.AddField(
            model_name="gym",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Среднее арифметическое всех оценок",
                max_digits=3,
                verbose_name="Средний рейтинг",
            ),
        ),
        migrations.CreateModel(
            name="GymReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_reviews",
                        to="fitness.gym",
                        verbose_name="Спортивный зал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_reviews",
                        to="fitness.userprofile",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв на зал",
                "verbose_name_plural": "Отзывы на залы",
                "db_table": "gym_reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["gym"], name="gym_reviews_gym_id_13fa34_idx"),
                    models.Index(
                        fields=["rating"], name="gym_reviews_rating_2e5a68_idx"
                    ),
                ],
                "unique_together": {("user", "gym")},
            },
        ),
    ]
